### ISSUE TITLE
[Bug] Bare Board Bootstrapping Blues

### ISSUE THREAD

**Issue by robertlipe** [BlueAndi/esp-rgb-led-matrix#137]
**Describe the bug**
I have an [extremely](https://wiki.luatos.com/chips/esp32s3/board.html) bare S3 board.  I successfully built and flashed the code. (Yay!) I looked for a way to break the deadlock of having no WiFi to configure WiFi. I was prepared to edit a config file and just build it into the image, but learned that you have to ground GPIO4 for some time in order to get either to a serial console (the default doesn't accept inout) or to get a WiFi hotspot mode so you can configure the board.

So far, I can't get to either one.

**To Reproduce**
1. Build and install to new ESP32-S3 board without screen, keys
2. Look for way to configure WiFi via software, denied.
3. Look for serial console. it's write-only.
4. Used WiFi scanner to find new AP, hoping I could hop to the config page. No new radio observed.
**Expected behavior**
I gathered I should be able to ground GPIO 4 and be presented with a serial console (none is available) or a new WiFi AP running in local mode that I should be able to join and then use THAT to configure WiFi fully enough to get the device booted to local LAN. 

No joy.

**Screenshots**
ESP-ROM:esp32s3-20210327
Build:Mar 27 2021
rst:0x1 (POWERON),boot:0x10 (DOWNLOAD(USB/UART0))
waiting for download
[   397][E][Preferences.cpp:483] getString(): nvs_get_str len fail: ha_dp NOT_FOUND
[   417][E][Preferences.cpp:483] getString(): nvs_get_str len fail: mqtt_broker_url NOT_FOUND
[   418][E][Preferences.cpp:483] getString(): nvs_get_str len fail: hostname NOT_FOUND
[  5398][E][Preferences.cpp:483] getString(): nvs_get_str len fail: hostname NOT_FOUND
[  7421][E][Preferences.cpp:483] getString(): nvs_get_str len fail: hostname NOT_FOUND
[  7474][E][Preferences.cpp:483] getString(): nvs_get_str len fail: web_login_user NOT_FOUND
[  7474][E][Preferences.cpp:483] getString(): nvs_get_str len fail: web_login_pass NOT_FOUND
[  7484][E][Preferences.cpp:483] getString(): nvs_get_str len fail: web_login_user NOT_FOUND
[  7488][E][Preferences.cpp:483] getString(): nvs_get_str len fail: web_login_pass NOT_FOUND
[  8045][E][vfs_api.cpp:105] open(): /littlefs/configuration/4176.sprite does not exist, no permits for creation
[  8052][E][vfs_api.cpp:105] open(): /littlefs/configuration/4176.bmp does not exist, no permits for creation
[  8070][E][Preferences.cpp:483] getString(): nvs_get_str len fail: hostname NOT_FOUND
[  8146][E][vfs_api.cpp:182] remove(): /configuration/4176.sprite does not exists or is directory
[  8299][E][Preferences.cpp:483] getString(): nvs_get_str len fail: sta_ssid NOT_FOUND
[  8299][E][Preferences.cpp:483] getString(): nvs_get_str len fail: sta_passphrase NOT_FOUND
[   397][E][Preferences.cpp:483] getString(): nvs_get_str len fail: ha_dp NOT_FOUND
[   417][E][Preferences.cpp:483] getString(): nvs_get_str len fail: mqtt_broker_url NOT_FOUND
[   418][E][Preferences.cpp:483] getString(): nvs_get_str len fail: hostname NOT_FOUND
[  5399][E][Preferences.cpp:483] getString(): nvs_get_str len fail: hostname NOT_FOUND
[  7421][E][Preferences.cpp:483] getString(): nvs_get_str len fail: hostname NOT_FOUND
[  7460][E][Preferences.cpp:483] getString(): nvs_get_str len fail: web_login_user NOT_FOUND
[  7461][E][Preferences.cpp:483] getString(): nvs_get_str len fail: web_login_pass NOT_FOUND
[  7471][E][Preferences.cpp:483] getString(): nvs_get_str len fail: web_login_user NOT_FOUND
[  7474][E][Preferences.cpp:483] getString(): nvs_get_str len fail: web_login_pass NOT_FOUND
[  8021][E][vfs_api.cpp:105] open(): /littlefs/configuration/4176.sprite does not exist, no permits for creation
[  8029][E][vfs_api.cpp:105] open(): /littlefs/configuration/4176.bmp does not exist, no permits for creation
[  8047][E][Preferences.cpp:483] getString(): nvs_get_str len fail: hostname NOT_FOUND
[  8119][E][vfs_api.cpp:182] remove(): /configuration/4176.sprite does not exists or is directory
[  8267][E][Preferences.cpp:483] getString(): nvs_get_str len fail: sta_ssid NOT_FOUND
[  8267][E][Preferences.cpp:483] getString(): nvs_get_str len fail: sta_passphrase NOT_FOUND
[   397][E][Preferences.cpp:483] getString(): nvs_get_str len fail: ha_dp NOT_FOUND
[   417][E][Preferences.cpp:483] getString(): nvs_get_str len fail: mqtt_broker_url NOT_FOUND
[   418][E][Preferences.cpp:483] getString(): nvs_get_str len fail: hostname NOT_FOUND
[  5399][E][Preferences.cpp:483] getString(): nvs_get_str len fail: hostname NOT_FOUND
[  7421][E][Preferences.cpp:483] getString(): nvs_get_str len fail: hostname NOT_FOUND
[  7461][E][Preferences.cpp:483] getString(): nvs_get_str len fail: web_login_user NOT_FOUND
[  7461][E][Preferences.cpp:483] getString(): nvs_get_str len fail: web_login_pass NOT_FOUND
[  7472][E][Preferences.cpp:483] getString(): nvs_get_str len fail: web_login_user NOT_FOUND
[  7475][E][Preferences.cpp:483] getString(): nvs_get_str len fail: web_login_pass NOT_FOUND
[  8022][E][vfs_api.cpp:105] open(): /littlefs/configuration/4176.sprite does not exist, no permits for creation
[  8030][E][vfs_api.cpp:105] open(): /littlefs/configuration/4176.bmp does not exist, no permits for creation
[  8048][E][Preferences.cpp:483] getString(): nvs_get_str len fail: hostname NOT_FOUND
[  8120][E][vfs_api.cpp:182] remove(): /configuration/4176.sprite does not exists or is directory
[  8268][E][Preferences.cpp:483] getString(): nvs_get_str len fail: sta_ssid NOT_FOUND
[  8268][E][Preferences.cpp:483] getString(): nvs_get_str len fail: sta_passphrase NOT_FOUND

I can't find Preferences.cpp in the source. Otherwise, I'd just edit in SSID network configuration.

No new radio presents. This means that [Variant 1](https://github.com/BlueAndi/esp-rgb-led-matrix/tree/master#very-first-startup) isn't an option.
I get serial debugging, but nothing like a console.  No input is accepted. This means that[ Variant 2 ](https://github.com/BlueAndi/esp-rgb-led-matrix/tree/master#very-first-startup)isn't an option.

I've tried holding GPIO4 long for extended time. No change in screen action and no input is accepted or even echoed.

The onboard LED turns blue and I definitely see WS2812 signal on pin 5 (or whatever it was - it was las night that I configured that, but the described pin is exactly where I found the signal and I confirmed that a small NeoPixel ring light did indeed do NeoPixel stuff.

**Please complete the following information:**
 - Development board: [Generic](https://wiki.luatos.com/chips/esp32s3/board.html) ESP32-S3 board
 - Version: [e.g. 6.0.0] I tried rolling back to 2454575e to get the release, but very little code has been checked in since the release, so I doubt this is recent (post-release) breakage.
 
 I'm not hyper concerned about security. I'm totally willing to edit source to contain login information. I'm willing to change something to 'if true' if it means I can get to a serial console or get an internal AP started. There may be a doc issue on the GPIO4 thing and there may be issue in the code recognizing a "long key press" that's actually a jumper wire in my case. Selfishly, I'm less interested in debugging that than just getting to a workable configuration, whether that's by changing code to start the serial console, start the WiFI AP, or even just compiling in passwords.
 
 Any recommendations on ways to "hot wire" the configuration to get it started?
 
 Thank you!

**Additional context**
I suspect existing users (of supported hardware) aren't affected. They have their credentials already on the littlefs/spiffs. I think this is just new user bootstrapping issue. 

Is that GPIO configured with an internal pull-up? If it's left floating, maybe we're not seeing a solid edge as we transition GPIO4 to ground.

**Log**
From a fresh reset:
Connected.
[   397][E][Preferences.cpp:483] getString(): nvs_get_str len fail: ha_dp NOT_FOUND
[   417][E][Preferences.cpp:483] getString(): nvs_get_str len fail: mqtt_broker_url NOT_FOUND
[   418][E][Preferences.cpp:483] getString(): nvs_get_str len fail: hostname NOT_FOUND
[  5399][E][Preferences.cpp:483] getString(): nvs_get_str len fail: hostname NOT_FOUND
[  7421][E][Preferences.cpp:483] getString(): nvs_get_str len fail: hostname NOT_FOUND
[  7461][E][Preferences.cpp:483] getString(): nvs_get_str len fail: web_login_user NOT_FOUND
[  7461][E][Preferences.cpp:483] getString(): nvs_get_str len fail: web_login_pass NOT_FOUND
[  7472][E][Preferences.cpp:483] getString(): nvs_get_str len fail: web_login_user NOT_FOUND
[  7475][E][Preferences.cpp:483] getString(): nvs_get_str len fail: web_login_pass NOT_FOUND
[  8022][E][vfs_api.cpp:105] open(): /littlefs/configuration/4176.sprite does not exist, no permits for creation
[  8030][E][vfs_api.cpp:105] open(): /littlefs/configuration/4176.bmp does not exist, no permits for creation
[  8048][E][Preferences.cpp:483] getString(): nvs_get_str len fail: hostname NOT_FOUND
[  8120][E][vfs_api.cpp:182] remove(): /configuration/4176.sprite does not exists or is directory
[  8268][E][Preferences.cpp:483] getString(): nvs_get_str len fail: sta_ssid NOT_FOUND
[  8268][E][Preferences.cpp:483] getString(): nvs_get_str len fail: sta_passphrase NOT_FOUND

By themselves, these don't seem too alarming on a first boot. (Well, the /littlefs failure are, but only a little...) It's the inability to further make progress that's bumming me out.

**Comment by BlueAndi** [comment]
Hi Robert,
can you show me your board configuration? I am wondering that the serial connection shows only the logs of the Arduino part, but not from the Pixelix application. Hmm ...

On the other hand to just configure your wifi crendentials add them after the whole if/else block:
https://github.com/BlueAndi/esp-rgb-led-matrix/blob/d02f4732a3f04be2213966291e33f5abce7f6406/src/StateMachine/ConnectingState.cpp#L72-L88

like

```cpp
m_wifiSSID = "...";
m_wifiPassphrase = "...";
```

**Comment by BlueAndi** [comment]
And just for a little bit of debugging :-) ... can you add this to your board configuration and check whether you now can use the serial terminal?

```
-D ARDUINO_USB_MODE=1
-D ARDUINO_USB_CDC_ON_BOOT=1
```

**Comment by BlueAndi** [comment]
You are welcome ... especially on the embedded world. :-)
First the choosen development board "lilygo-t-display-s3" expects to have a TFT display connected and the button is on a different pin. You mentioned to have a WS2812 led matrix connected to GPIO 5, so we need a different configuration.

I configured a separate board, this maybe makes it easier. Please checkout the branch https://github.com/BlueAndi/esp-rgb-led-matrix/tree/support/LuatOS-esp32s3

And try "luatos-esp32s3".

Here you can see the configuration:
https://github.com/BlueAndi/esp-rgb-led-matrix/blob/e122ffb85154ae0d505617899516df82d139cbaa/config/board.ini#L290-L338

Its a first shot based on the documentation and your comments ... keep fingers crossed and try.

You can add your wifi credentials to the same place of course. My assumption is that with your jumper on GPIO 4 it should work now as well to start the access point mode.

If Pixelix is connected to your wifi network, you will (should) be able to connect to the internal webserver. As well as in access point mode.

**Comment by BlueAndi** [comment]
Hi Robert, I am on a business trip since today. Will come back if I am back at home. Just to note, I thought putting the stuff to a branch and improve it there is easier than pushing fragments over the issue. :-)

**Comment by BlueAndi** [comment]
> The lilygo baseline almost works. Building the devkitc baseline does not. If I kept the luatos configuration active, but based it on lilygo, things look up a tad.

> -board = esp32-s3-devkitc-1
> +; board = esp32-s3-devkitc-1^M
> +board = lilygo-t-display-s3^M

By changing this, you always compile the Lilygo with the same result. Was the flash size problem the only one with the LuatOS ESP32 S3 configuration?
Please stay with the luatos-esp32-s3 configuration (without additional changes, except wifi credentials). I updated the configuration for 16 MB flash and set the memory type like for the Lilygo. Now you can try again.

**Comment by BlueAndi** [comment]
And I saw right now in the schematic, that you can choose between direct USB CDC and usb-to-uart ... I guess the real Pixelix log output will be shown by changing the jumper.
![image](https://github.com/BlueAndi/esp-rgb-led-matrix/assets/9699465/1e411902-610f-4bce-970d-3061d412f280)

**Comment by BlueAndi** [comment]
Hi @robertlipe any success with my previous changes in the branch?

**Comment by BlueAndi** [comment]
Let's try two things:
1. Use the luatos-esp32-s3 environment, remove this line https://github.com/BlueAndi/esp-rgb-led-matrix/blob/6dc41533ff30ab4e6374e9808e80024e89168e0b/config/board.ini#L307 , then rebuild and try. Whats the result?
2. Continue by replacing this line https://github.com/BlueAndi/esp-rgb-led-matrix/blob/6dc41533ff30ab4e6374e9808e80024e89168e0b/config/board.ini#L297 with lilygo-t-display-s3. Whats the result?

Just to note, I will be off for some days, starting from tomorrow ... need vacation. :-)

**Comment by BlueAndi** [comment]
Hi Robert,
I am back ... unfortunately :-) ... although the luatos wiki talks about supporting 8 MB PSRAM, it seems not to be available on your board or maybe not compatible with the current pio setup. Lets remove BOARD_HAS_PSRAM. At the moment Pixelix doesn't use PSRAM internally, its planned for the future.

Correct me if I am wrong, but now without PSRAM support the logs are looking similar between the lilygo-t-display-s3 configuration and the luatos-esp32s3 configuration ... except the warning(s) about a pin, but we can skip this for a moment.

The previous logs are all three with the luatos-esp32s3 configuration, right (its mentioned at the begin of every log). But funny with different number of ```__pinMode(): Invalid pin selected``` warnings. :-?

We should keep going now only with the luatos-esp32s3 configuration, because it supports the led matrix with WS28xx support. The lilygo-t-display-s3 expects to have a TFT display.

BTW these kind of logs ```[  3009][E][Preferences.cpp:483] getString(): nvs_get_str len fail:
hostname NOT_FOUND``` are coming from the underlying esp32 Arduino library and although logged as error, they are not.
Pixelix reads at startup from a persistent storage partition to check for overwritten default values. If there is no explicit value, this error appears, but Pixelix will just use the default value which is ok.

The mesmerizer/nightdriverled seems to be private, I can not see it.

I will check how to route the Pixelix logs through the right uart, this should give us much better information.

**Comment by BlueAndi** [comment]
Could you try ```Serial.setDebugOutput(true);``` before the println and have a look to the logs?:
https://github.com/BlueAndi/esp-rgb-led-matrix/blob/2454575e59d70b5b51ec63b5f4856521662b1e11/src/main.cpp#L156-L166

**Comment by BlueAndi** [comment]
> As I learn more about the ESP parts, the more frustrating it is to find out what I actually HAVE on any given board. When I last poked at this, my working theory was that the dual/quad/octo speed SPI for the PSRAM. I could find that some ESP32-S3's would do octal and some wouldn't and that the symptoms were the same kind of " PSRAM ID read error: 0x00ffffff" read error. There a lot of platformio (ESP-IDF?) gibberish that has to be passed to distinguish between the quad and octal configurations, for example, and I think that's where we're currently stuck. But that's a theory.

I found a bug in the configuration and fixed it. Now we should go with quad i/o (qio) and octal peripheral interface (opi) access. Please pull and clean build. This looks like the difference between the lilygo board config and the devkit config. Its not always straight forward how to overwrite the board configurations.

But yes, you are right. You need to know the detail to configure the stuff correct.
This datasheet shows it a little bit: https://www.espressif.com/sites/default/files/documentation/esp32-s3_datasheet_en.pdf



> If so, that's mystery #4. You're clearly a smart dude and wouldn't write a kilobyte of crap before initializing the UART. You wouldn't do it in two different threads or otherwise separate time domains. Even if you were this silly (you're not) the "fix" would always happen about the same time. So is there maybe something ELSE that's trying to control the serial port? I mean, we're compiling every opcode it can execute so we can't exactly accuse some TSR in your autoexec.bat (from 30 years ago...) or something, but it doesn't make sense that it doesn't resynchronize at one consistent point. Is there maybe a debug and a main thread both controlling the UART?


The esp32s3 has 3 uart's and for logging its getting more complicated depended on the development board considering the usb part. The luatos board schematic shows this:
![image](https://github.com/BlueAndi/esp-rgb-led-matrix/assets/9699465/77985d75-18d2-4a6d-91a0-fbff91c8109e)
![image](https://github.com/BlueAndi/esp-rgb-led-matrix/assets/9699465/21bb58cc-209e-49d8-a090-ec20887309fc)

What we see is, that the log_e() is shown on the console, because it uses uart0 (esp_tx/esp_rx). With the current setup, the Serial object is created by ```HWCDC Serial;```. That means Serial.println() goes with CDC (USB Communication Device Class) and not over uart0.

On your board is this small switch here:
![image](https://github.com/BlueAndi/esp-rgb-led-matrix/assets/9699465/5ed9d3f9-8f60-45bd-a08c-dfa70f817ab6)

This is the S2 which should select between uart0 and usb cdc. Did you try to switch it?

The other test is to try (keeping the S2 as it is)
```cpp
Serial0.println("test test");
```
As I can see you tested only Serial1 and Serial2 until now, right?

autoexec.bat .... LOL ... installing the TSRs there or handling the emm386 and highmem stuff there ... yeah ... long time ago ...



> Nightdriverled.com is not private. 'mesmerizer' is the project, err,

Oh, I see ... I tried https://github.com/mesmerizer/nightdriverled :-)

**Comment by BlueAndi** [comment]
> Excellent! I think that's one of our major mysteries down. Thank you.

You are welcome! :-) Thank you for the long breath, sometimes I get github issues and I ask back, but never receive any further answer.


> Indeed. I remember developing disgust with Scons years ago for that very reason. I moved on to other facets of the same project that used a different build system. Then I retired/disabled and find myself now back on projects using a thing coat of lipstick over...scons.

I am not that familiar with Scons, so sometimes these kind of mistakes happen. Looks like others try to hide the Scons interface or close some holes there. Did you have an accident, forced you to retire?


> It's super frustrating how sometimes it's the CHIP number and sometimes it's the MODULE number and sometimes the BOARD number. (I get they're three different things and may indeed be different; i'm just explaining frustration.) So board ZZZ might have module number WROOM-E which might have chip ESP32-S3, but somehow, somewhere, there are additional markings somewhere that describe the "DOWD" or "N8R16" traits, which I could see going into any of those three camps - I see empty solder pads for PSRAM, so is the PSRAM that's present small enough to be inside the package, but on a dfferent wafer? I've heard that's a thing, but I can't exactly start delidding things. Sorry for the rant.

No problem. In business currently I am dealing with Infineon Aurix MCUs and the chip id is long, but very important to see all the features you have or you miss.  Empty solder pads means no PSRAM, because according to the schematic its a esp32-s3fn8 which has no inside-package PSRAM, see this snippet from the datasheet:
![image](https://github.com/BlueAndi/esp-rgb-led-matrix/assets/9699465/1fc82c8f-150f-4449-8a12-a7d72286d4a0)

You can modify the code and check whether you really have PSRAM or not.



> Oh, in vaguely related news, are you in North America? I think the tooth fairy is about to bring me another of these boards and I could forward you one, but if you're not in the US, postage would probably dwarf it. Maybe I should just send you an Amazon gift card to cover one if that doesn't work.

No, I am living in Germany. I already searched on Amazon (.de) for these development boards, but couldn't find them. They seem to be available only on the .com website. Thanks for the offer.



> Side rant: Damn, this python dependency finder thing is slow. My machine should be able to easily build all the software on the board in less time than it takes to figure out what to build. Activity monitor shows python taking way more CPU than any of the compiler invocations and rarely are we compiling on > 1 core. Six minute "do nothing" build times are just embarrassing.


Yes, its slow on my side as well. I am not sure but I guess they do a lot of internet traffic in the background to check for the libs which consumes a lot of time too.




> Finally, stuff that actually looks like your project! :-)

Hoorrayyy! :-)




> So, we may be coming out of the weeds. ...but there's still no web server coming up on the IP address listed at the end of the posted stnippet. Are we back into the 'solvable' problems now?


Hmm ... a simple http://192.168.2.168 should have done it ... I can't see any error message about.
Please try: ```$ curl -u luke:skywalker -X GET http://192.168.2.168/rest/api/v1/status```
Just to see whether we get a response this way.

If not, please try to ping it.

**Comment by BlueAndi** [comment]
Enjoy the trip with your family. Didn't know that there are such strange german birds around. *LOL*

**Comment by BlueAndi** [comment]
Hi Robert, hope you are back from the mountains, or maybe already there agin? :-D

Is this still an issue or could we close it?
