### ISSUE TITLE
What case?

### ISSUE THREAD

**Issue by pnichols77** [BlueAndi/esp-rgb-led-matrix#66]
Hi -  what case are you using to hold it all together?

**Comment by BlueAndi** [comment]
Hi,
the current case I use this one:
https://www.thingiverse.com/thing:2791276
in combination with that
https://www.thingiverse.com/thing:3884621

The future plan is to have a own case, which considers several ideas e.g. with integrated LDR and etc.
But because I have no 3d printer, this may take some time. :-)

**Comment by pnichols77** [comment]
Thank you!

**Comment by BlueAndi** [comment]
You are welcome.
