### ISSUE TITLE
how do I run real-time development locally

### ISSUE THREAD

**Issue by Tokyo-Lei** [BlueAndi/esp-rgb-led-matrix#85]
Hello, how do I run real-time development locally?

do not need to build and upload to the device. You can directly debug vscode in windows and see the web page for interactive development 。

**Comment by BlueAndi** [comment]
Hi,
I don't use any local real-time development feature like in angular, react or vuejs. Its plain written HTML5 in combination with Bootstrap and jquery. Some page content is injected by the target itself, some other is requested via websocket or REST API.
Jumping on e.g. vuejs is not an option right now considering the 4 MB modules, because the filesystem has only 150000h byte for the filesystem itself.

For the development you can use the online editor provided via webserver, see menu "Development -> File Editor". Use CTRL + S to save your changes.
